#!/bin/bash

# include the libraries
source 'lib/all'

# initial values
ip=''
portsPositive=()
portsNegative=()
sslCheck=()

# declare parameter list array
PARAMETERS=()

currentDomain=""

# read arguments
while [[ $# > 0 ]]; do
  case "$1" in
    #
    # port positive
    #
    -pp|-p+|--portPositive)
      portsPositive+=("$2")
      shift
    ;;
    -pp=*|-p+=*|--portNegative=*)
      portsPositive+=("${1#*=}")
    ;;

    #
    # port negative
    #
    -pn|-p-|--portNegative)
      portsNegative+=("$2")
      shift
    ;;
    -pn=*|-p-=*|--portNegative=*)
      portsNegative+=("${1#*=}")
    ;;

    #
    # domain name
    #
    -dn|--domainName)
        currentDomain="$2"
        shift
    ;;
    -dn=*|--domainName=*)
        currentDomain="${1#*=}"
    ;;

    #
    # ssl
    #
    -ssl)
        if [ "$currentDomain" == "" ]; then
            log 'error' "Please specifiy the domain name (-dn) first, before use -ssl option."
            exit
        fi

        sslCheck+=("$currentDomain")
    ;;

    #
    # collect these unknown parameters
    #
    *)
      PARAMETERS+=("$1")
    ;;
  esac
  shift
done

echo $currentDomain

# check ip parameter
if [ ${#PARAMETERS[@]} -lt 1 ]; then
    log 'error' "No server host name or ip address is given"
    exit
fi

# save the ip address
ip="${PARAMETERS[0]}"

allPassed=true

# check if server is running
if isPingableCheck "$ip"; then
    pingable=true
else
    allPassed=false
fi

# check positive ports
for port in "${portsPositive[@]}"; do
    if ! isPortOpenCheck "$ip" "$port"; then
        allPassed=false
    fi
done

# check negative ports
for port in "${portsNegative[@]}"; do
    if ! isNotPortOpenCheck "$ip" "$port"; then
        allPassed=false
    fi
done

domain='expo.apo-ident.hiperscan.rsm-service.de'

# check if domain is assigned to this server
if ! isDomainAssignedToIpCheck "$domain" "$ip"; then
    allPassed=false
fi

# check http to https redirection
url="http://expo.apo-ident.hiperscan.rsm-service.de"
expectedStatusCode="301"
if ! isHttpStatusCodeCheck "$url" "$expectedStatusCode"; then
    allPassed=false
fi

# check password protection (request without authentication)
url="https://expo.apo-ident.hiperscan.rsm-service.de"
expectedStatusCode="401"
if ! isHttpStatusCodeCheck "$url" "$expectedStatusCode"; then
    allPassed=false
fi

# check password protection (request with authentication)
url="https://rsm:rsm2017@expo.apo-ident.hiperscan.rsm-service.de"
expectedStatusCode="200"
if ! isHttpStatusCodeCheck "$url" "$expectedStatusCode"; then
    allPassed=false
fi

#domain="www.500landinitiativen.de"
#domain="www.awarion.rsm-service.de"
#domain="live.haustierportal.bmel.rsm-development.de"
#domain="app.ppdash.ddhome.rsm-development.de"
for domain in "${sslCheck[@]}"; do
    certFile="/tmp/$domain.crt"
    chainfile="/tmp/$domain.ca"

    # get and save domain cert
    cert=$(getDomainCert "$domain")
    echo "$cert" > "$certFile"

    # get the issuer from domain cert
    issuer=$(getIssuer "$domain")

    # get and save the issuer certificate
    certChain=$(getChainCertificate "$domain")
  
    if [ "$certChain" == "" ]; then 
        log 'failed' "No chain certificate returned."
        allPassed=false
    else
        echo "$certChain" > "$chainfile"

        # check the certificates
        if ! isCertificateValid "$certFile" "$chainfile" "$domain"; then
            allPassed=false
        fi
        if ! isChainCertificateValid "$chainfile" "$issuer"; then
            allPassed=false
        fi

        # gets the status
        if ! isStatusOcspOk "$domain" "$chainfile" "$certFile"; then
            allPassed=false
        fi
    fi
done

# print all check status
if $allPassed; then
    log "passed" "All checks passed."
else
    log "failed" "At least one check is not passed."
fi


