#!/bin/bash

# include the libraries
source 'lib/all'
source 'parameter'

# check ip parameter
if [ ${#PARAMETERS[@]} -lt 1 ]; then
    log 'error' "No server host name or ip address is given"
    exit
fi

# save the ip address
ip="${PARAMETERS[0]}"

allPassed=true

# check if server is running
if isPingableCheck "$ip"; then
    pingable=true
else
    allPassed=false
fi

# check positive ports
for port in "${portsPositive[@]}"; do
    if ! isPortOpenCheck "$ip" "$port"; then
        allPassed=false
    fi
done

# check negative ports
for port in "${portsNegative[@]}"; do
    if ! isNotPortOpenCheck "$ip" "$port"; then
        allPassed=false
    fi
done

# a record check
for domain in "${!aRecords[@]}"; do
    if ! isDomainAssignedToIpCheck "$domain" "$ip"; then
        allPassed=false
    fi
done

# status code check
for url in "${!statusCodeCheck[@]}"; do
    ports="${statusCodeCheck[$url]}"

    if ! isHttpStatusCodeCheck "$url" "$ports"; then
        allPassed=false
    fi
done

# ssl check
for domain in "${sslCheck[@]}"; do
    certFile="/tmp/$domain.crt"
    chainfile="/tmp/$domain.ca"

    # get and save domain cert
    cert=$(getDomainCert "$domain")
    echo "$cert" > "$certFile"

    # get the issuer from domain cert
    issuer=$(getIssuer "$domain")

    # get and save the issuer certificate
    certChain=$(getChainCertificate "$domain")
  
    if [ "$certChain" == "" ]; then 
        log 'failed' "No chain certificate returned."
        allPassed=false
    else
        echo "$certChain" > "$chainfile"

        # check the certificates
        if ! isCertificateVerified "$certFile" "$chainfile" "$domain"; then
            allPassed=false
        fi
        if ! isChainCertificateVerified "$chainfile" "$issuer"; then
            allPassed=false
        fi
        if ! isCertificateValid "$certFile" "$domain"; then
            allPassed=false
        fi
        if ! isDomainFromCertificate "$domain" "$certFile"; then
            allPassed=false
        fi

        # gets the status
        if ! isStatusOcspOk "$domain" "$chainfile" "$certFile"; then
            allPassed=false
        fi
    fi
done

# print all check status
if $allPassed; then
    log "passed" "All checks passed."
else
    log "failed" "At least one check is not passed."
fi


