#!/bin/bash

# ------------
# A install script to install the public scripts.
#
# @author    Björn Hempel <bjoern@hempel.li>
# @date      2017-04-26
# @version   1.0
#
# @copyright ISC License
# @copyright
# @copyright Copyright (c) 2017, Björn Hempel
# @copyright
# @copyright Permission to use, copy, modify, and/or distribute this software for any
# @copyright purpose with or without fee is hereby granted, provided that the above
# @copyright copyright notice and this permission notice appear in all copies.
# @copyright
# @copyright THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# @copyright REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# @copyright AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# @copyright INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# @copyright LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# @copyright OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# @copyright PERFORMANCE OF THIS SOFTWARE.
# @copyright
# @copyright Written by Björn Hempel <bjoern@hempel.li>.
# ------------

# some configs before
pathRoot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# git settings
friendsOfBashGitUri="git://github.com/bjoern-hempel/friends-of-bash.git"
projectGitUri="git://github.com/bjoern-hempel/service-checker.git"

# project settings
            projectPathLocal="$pathRoot"
           projectPathRemote="/opt/service-checker"
           projectUsageLocal="bin/checker --help"
          projectUsageRemote="service-checker --help"
projectInstallSuccessMessage="The service-checker is installed in the folder \"%s\"."
  projectInstallErrorMessage="Error occurred while installing the service checker into \"%s\"."
       projectInstallMessage="Try to install the service-checker to \"%s\"."

declare -A installableApps
    installPath="/usr/local/bin"
     sourcePath="$projectPathRemote/bin"
installableApps=([checker]=service-checker)

# initialize the install process
source "$pathRoot/lib/initInstall"

# detect friends of bash library → $friendsOfBashInclude
source "$pathRoot/lib/fobDetection"

# a success message
log "success" "The friends of bash library was found in the folder \"$friendsOfBashPath\"."

if $GLOBAL_INSTALLATION; then
    if gitInstall "$projectGitUri" "$projectPathRemote" "$projectInstallMessage" "$projectInstallSuccessMessage" "$projectInstallErrorMessage"; then

        # install all given apps
        for app in "${!installableApps[@]}"; do
            appTo="${installableApps[$app]}"
            installApp "$sourcePath/$app" "$installPath/$appTo"
        done
    else
        exit 1
    fi
fi

# a success message - finish here
log "success" "The installation script was executed successfully."
if $GLOBAL_INSTALLATION; then
    log "info" "Now you can use the service-checker with \"$projectUsageRemote\"."
else
    log "info" "Now you can use the service-checker with \"$projectUsageLocal\"."
fi

